name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Check formatting with Black
      run: |
        black --check --diff .
    - name: Type check with mypy
      run: |
        mypy src/netenum tests
    - name: Lint with Pylint
      run: |
        pylint src/netenum tests
    - name: Lint with Flake8
      run: |
        flake8 src/netenum tests 
        pylint src/netenum 